"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {RoomChat} from '@/components/room-chat';
import {apiBase} from '@/lib/api';
import {EmptyState,Icon,PageHeading} from '@/components/ui';
type Candidate={user_id:string;name:string;score:number;matched_skills:string[]};
type Room={id:string;title:string;members:string[];unread_count:number};
async function request(path:string,data?:unknown){const r=await fetch(apiBase+path,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'操作失败，请检查连接或权限');return d;}
export default function Teams(){
 const [skills,setSkills]=useState('Python,AI'),[candidates,setCandidates]=useState<Candidate[]>([]),[rooms,setRooms]=useState<Room[]>([]),[room,setRoom]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[myId,setMyId]=useState(''),[busy,setBusy]=useState(false),[matched,setMatched]=useState(false),[loading,setLoading]=useState(true),[demo,setDemo]=useState(false);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setStatus('');try{await action()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let stopped=false;async function refresh(){try{const items:Room[]=await request('/v1/rooms');if(!stopped){setRooms(items);const selected=new URLSearchParams(window.location.search).get('room');setRoom(current=>items.some(x=>x.id===current)?current:selected&&items.some(x=>x.id===selected)?selected:items[0]?.id||'')}}catch(e){if(!stopped)setError((e as Error).message)}finally{if(!stopped)setLoading(false)}}void refresh();request('/v1/profile').then(p=>{if(!stopped)setMyId(p.user_id)}).catch(e=>{if(!stopped)setError(e.message)});const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},5000);return()=>{stopped=true;clearInterval(timer)}},[]);
 const selected=rooms.find(r=>r.id===room);
 return <div className="shell"><PageHeading eyebrow="CONVERSATIONS & COLLABORATION" title="交流空间" description="把讨论留在共同的空间，和队友一起推进事情。"><Link href="/team-manager" className="button primary"><Icon name="users" size={15}/>管理我的团队</Link></PageHeading>
  <details className="card" open={matched||undefined}><summary>寻找互补的队友</summary><p>匹配已开启展示的同校用户。学校信息由本人填写，尚未核验学籍。</p><form className="match-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await request('/v1/tools/team_match',skills.split(/[,，]/).map(s=>s.trim()).filter(Boolean));setCandidates(result.items);setDemo(result.demo);setMatched(true)})}}><label htmlFor="match-skills">需要的技能</label><input id="match-skills" value={skills} maxLength={300} placeholder="例如 React,设计" onChange={e=>setSkills(e.target.value)}/><button className="primary" disabled={busy||!skills.trim()}>{busy?'正在处理…':'匹配队友'}</button></form>{matched&&demo&&<p className="field-hint">本次匹配包含模拟账号，仅用于功能演示。</p>}{matched&&!candidates.length&&<EmptyState icon="users" title="暂无匹配的同学" description="试着调整技能关键词，也可以创建自己的团队。"/>}<div className="candidate-grid">{candidates.map(c=><article className="card" key={c.user_id}><span className="user-avatar">{c.name.slice(0,1)}</span><h2>{c.name}</h2><p>技能匹配 {c.score}%</p><div className="tagrow">{c.matched_skills.map(s=><span key={s}>{s}</span>)}</div><button disabled={busy} onClick={()=>void run(async()=>{const r=await request('/v1/tools/message_connect',{target:c.user_id});setRooms(await request('/v1/rooms'));setRoom(r.id);setStatus('会话已建立，可以开始交流')})}>确认建立联系</button></article>)}</div></details>
  {error&&<p role="alert">{error}</p>}{status&&<p role="status" className="feedback">{status}</p>}
  <div className="room-workspace"><aside className="room-list" aria-label="我的会话"><h2>MY CONVERSATIONS</h2>{loading&&<p className="field-hint">正在读取会话…</p>}{rooms.map(r=><button aria-label={r.title} className={'room-select '+(room===r.id?'active':'')} key={r.id} onClick={()=>{setRoom(r.id);setError('');window.history.replaceState(null,'','/teams?room='+encodeURIComponent(r.id))}}><Icon name="hash" size={15}/><span className="truncate">{r.title}<small>{r.members.length} 位成员</small></span>{r.unread_count>0&&<span className="room-unread">{r.unread_count}</span>}</button>)}{!loading&&!rooms.length&&<p className="field-hint">还没有加入会话。</p>}</aside><section className="room-content">{selected?<><div className="room-header"><div><h2>{selected.title}</h2><p>{selected.members.length} 位成员 · 消息仅对房间成员可见</p></div>{selected.members.length===2&&<button className="quiet" disabled={busy} onClick={()=>{if(window.confirm('拉黑后双方不能继续发送消息。是否继续？'))void run(async()=>{const target=selected.members.find(x=>x!==myId);if(target){await request('/v1/blocks',{target});setStatus('已拉黑，双方不能继续发送消息')}})}}>拉黑对方</button>}</div><RoomChat key={room} roomId={room} myId={myId}/></>:<EmptyState icon="users" title="从一次交流开始" description="创建团队后进入团队房间，或通过技能匹配和同学建立联系。" href="/team-manager" label="创建或加入团队"/>}</section></div>
 </div>
}
