'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {apiBase} from '@/lib/api';
import {Icon} from '@/components/ui';
type Step={id:number;title:string;done:boolean};
export function PlanPreparation({planId,title,done}:{planId:number;title:string;done:boolean}){
 const [open,setOpen]=useState(false),[steps,setSteps]=useState<Step[]>([]),[loaded,setLoaded]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const base=`${apiBase}/v1/plans/${planId}`;
 useEffect(()=>{if(!open||loaded)return;let active=true;setLoading(true);fetch(base+'/steps').then(async r=>{const data=await r.json();if(!r.ok)throw Error('清单读取失败，请重试');if(active){setSteps(data);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[open,loaded,base]);
 async function request(path:string,method:string,body?:unknown){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'操作失败，请重试');return data;}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,formData=new FormData(form);if(busy||loading)return;setBusy(true);setError('');try{const step=await request('/steps','POST',{title:String(formData.get('step'))});setSteps(xs=>xs.some(x=>x.id===step.id)?xs:[...xs,step]);form.reset();setMessage('清单条目已保存')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function update(step:Step,remove=false){if(busy)return;setBusy(true);setError('');try{const result=await request('/steps/'+step.id,remove?'DELETE':'PATCH',remove?undefined:{done:!step.done});setSteps(xs=>remove?xs.filter(x=>x.id!==step.id):xs.map(x=>x.id===step.id?result:x))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reminder(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,date=String(new FormData(form).get('remind'));setBusy(true);setError('');try{await request('/reminders','POST',{due_at:new Date(date).toISOString()});form.reset();setMessage('站内提醒已保存，届时可在通知中心查看')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="plan-preparation"><button className="preparation-toggle" aria-expanded={open} aria-controls={'preparation-'+planId} onClick={()=>setOpen(!open)}><Icon name="check" size={14}/>{open?'收起准备清单':'材料与准备清单'}{loaded&&<span>{steps.filter(s=>s.done).length}/{steps.length}</span>}</button>{open&&<div id={'preparation-'+planId}><p className="field-hint">这是你的个人清单。材料、数量和格式请对照官方通知填写。</p>{loading&&<p role="status">正在读取清单…</p>}{steps.map(step=><div className="preparation-step" key={step.id}><label><input type="checkbox" checked={step.done} disabled={busy} onChange={()=>void update(step)}/><span className={step.done?'complete':''}>{step.title}</span></label><button type="button" disabled={busy} aria-label={'删除清单条目：'+step.title} onClick={()=>void update(step,true)}><Icon name="close" size={12}/></button></div>)}{loaded&&!steps.length&&<small className="muted">还没有条目，从核对院系要求开始。</small>}<form onSubmit={add} className="preparation-add"><input name="step" aria-label={'新增清单条目：'+title} placeholder="如：按原文要求准备成绩单" required maxLength={300} disabled={busy||!loaded}/><button disabled={busy||!loaded} type="submit">添加</button></form>{!done&&<form className="preparation-reminder" onSubmit={reminder}><label>安排站内提醒（本地时间）<input name="remind" type="datetime-local" required disabled={busy} aria-label={'提醒时间：'+title}/></label><button disabled={busy} type="submit"><Icon name="bell" size={14}/>保存提醒</button></form>}{error&&<p role="alert">{error}</p>}{message&&<p role="status" className="feedback">{message} <Link href="/notifications">查看通知</Link></p>}</div>}</div>
}
