"use client";
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {apiBase,type Plan,type TrackerItem} from '@/lib/api';
import type {PathRecord} from '@/lib/catalog';
import {PlanPreparation} from '@/components/plan-preparation';
import {TrackerBoard} from '@/components/tracker-board';
import {EmptyState,Icon,PageHeading,dateLabel} from '@/components/ui';
const stages={todo:'待开始',doing:'进行中',done:'已完成'};
function PlanNote({note}:{note:string}){const reference=note.match(/^(?:模拟)?数据事项：\s*(\/data\/[a-f0-9-]{36})；原文：(https?:\/\/[^\s]+)$/i);return reference?<div className="feed-actions"><Link href={reference[1]}>查看关联事项</Link><a href={reference[2]} target="_blank" rel="noreferrer">核对原文</a></div>:<p>{note}</p>}
function localDate(value:string|null){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
export function PlansWorkspace({initial,tracker,paths,agentEnabled}:{initial:Plan[];tracker:TrackerItem[];paths:PathRecord[];agentEnabled:boolean}){
 const [plans,setPlans]=useState(initial),[tab,setTab]=useState('plans'),[filter,setFilter]=useState(''),[layout,setLayout]=useState('board'),[editor,setEditor]=useState<Plan|'new'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function save(payload:{title:string;path_id:number|null;due_date:string|null;status:Plan['status'];note:string},id?:number){const r=await fetch(apiBase+'/v1/plans'+(id?'/'+id:''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'保存失败，请检查内容');setPlans(xs=>id?xs.map(p=>p.id===id?d:p):[d,...xs]);setMessage('计划已保存');return d;}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),editing=editor&&editor!=='new'?editor:null;setBusy(true);setError('');try{await save({title:String(f.get('title')),path_id:f.get('path')?Number(f.get('path')):null,due_date:f.get('due')?new Date(String(f.get('due'))).toISOString():null,status:editing?.status||'todo',note:String(f.get('note'))},editing?.id);setEditor(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function status(p:Plan,next:Plan['status']){setBusy(true);setError('');try{await save({title:p.title,path_id:p.path_id,due_date:p.due_date,status:next,note:p.note},p.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const visible=plans.filter(p=>!filter||String(p.path_id)===filter),done=plans.filter(p=>p.status==='done').length;
 function card(p:Plan){return <article className="plan-card" key={p.id}><div className="feed-meta"><span>{paths.find(x=>x.id===p.path_id)?.name||'个人准备'}</span>{p.due_date&&<span className={p.status!=='done'&&new Date(p.due_date)<new Date()?'badge amber':'badge'}>{dateLabel(p.due_date)}</span>}</div><h3>{p.title}</h3>{p.note&&<PlanNote note={p.note}/>}<div className="plan-controls"><select aria-label={'更新计划状态：'+p.title} disabled={busy} value={p.status} onChange={e=>void status(p,e.target.value as Plan['status'])}>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="button-row">{agentEnabled&&p.status!=='done'&&<Link title="设置计划提醒" aria-label={'设置提醒：'+p.title} href={'/agent?intent=reminder&plan_id='+p.id}><Icon name="bell" size={14}/></Link>}<button disabled={busy} onClick={()=>{setEditor(p);setError('');setMessage('')}}>编辑</button></div></div><PlanPreparation planId={p.id} title={p.title} done={p.status==='done'}/></article>}
 return <div className="shell"><PageHeading eyebrow="MY ACTIONS" title="我的计划" description="把想做的事拆成下一步，让准备过程清楚可见。"><button className="primary" onClick={()=>{setTab('plans');setEditor('new');setMessage('');setError('')}}><Icon name="plus" size={15}/>新建计划</button>{agentEnabled&&<Link className="button secondary" href="/agent?intent=plan"><Icon name="spark" size={15}/>让校伴帮我规划</Link>}</PageHeading>
  <div className="tabs" role="tablist" aria-label="行动类别"><button role="tab" aria-selected={tab==='plans'} className={tab==='plans'?'active':''} onClick={()=>setTab('plans')}>个人计划 · {plans.length}</button><button role="tab" aria-selected={tab==='opportunities'} className={tab==='opportunities'?'active':''} onClick={()=>setTab('opportunities')}>机会行动 · {tracker.length}</button></div>
  {error&&<p role="alert">{error}</p>}{message&&<p className="feedback" role="status">{message}</p>}
  {tab==='opportunities'?<TrackerBoard initial={tracker}/>:<>
   {editor&&<form className="form-card" onSubmit={submit} key={editor==='new'?'new':editor.id}><h2>{editor==='new'?'创建一项个人计划':'编辑计划'}</h2><label>计划标题<input name="title" required maxLength={160} defaultValue={editor==='new'?'':editor.title} autoFocus placeholder="例如：整理三所目标院校的申请要求"/></label><div className="form-row"><label>所属路径<select name="path" defaultValue={editor==='new'?'':editor.path_id||''}><option value="">个人准备</option>{paths.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>个人截止时间（本地时间）<input name="due" type="datetime-local" defaultValue={editor==='new'?'':localDate(editor.due_date)}/></label></div><label>下一步与备注<textarea name="note" maxLength={2000} defaultValue={editor==='new'?'':editor.note} placeholder="写下准备完成的具体内容…"/></label><div className="button-row"><button className="primary" disabled={busy}>{busy?'保存中…':'保存计划'}</button><button type="button" disabled={busy} onClick={()=>setEditor(null)}>取消</button></div></form>}
   <div className="list-summary"><span>已完成 <b>{done}</b> / {plans.length} 项</span><div className="button-row"><select aria-label="筛选计划路径" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部路径</option>{paths.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button aria-label={layout==='board'?'切换为列表':'切换为看板'} onClick={()=>setLayout(layout==='board'?'list':'board')}><Icon name="filter" size={14}/>{layout==='board'?'列表':'看板'}</button></div></div>
   {!visible.length?<EmptyState icon="check" title={filter?'这个方向还没有计划':'从一件小事开始'} description="新建个人计划，或从信息中心选择一个事项加入。" href="/data" label="寻找感兴趣的信息"/>:layout==='board'?<div className="board">{Object.entries(stages).map(([k,v])=><section className="board-column" key={k} aria-label={v}><h2><span className="row"><i className="stream-dot" style={{background:k==='done'?'#78a68a':k==='doing'?'#669abe':'#b6c4ce'}}/>{v}</span><span>{visible.filter(p=>p.status===k).length}</span></h2>{visible.filter(p=>p.status===k).map(card)}{!visible.some(p=>p.status===k)&&<div className="board-empty">暂无{v}的计划</div>}</section>)}</div>:<div className="plan-list">{visible.map(card)}</div>}
  </>}
 </div>
}
