"use client";
import {useState,type FormEvent} from 'react';
import {apiBase,type Profile} from '@/lib/api';
import {streams} from '@/components/ui';
export function ProfileForm({initial}:{initial:Profile}){
 const [saved,setSaved]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const text=(key:string)=>String(f.get(key)||'').trim();const payload={display_name:text('display_name'),discoverable:f.get('discoverable')==='on',school:text('school'),college:text('college'),grade:text('grade'),major:text('major'),interests:text('interests').split(/[,，]/).map(x=>x.trim()).filter(Boolean),skills:text('skills').split(/[,，]/).map(x=>x.trim()).filter(Boolean),weekly_hours:Number(f.get('weekly_hours')),degree:text('degree'),target_year:f.get('target_year')?Number(f.get('target_year')):null,target_path:text('target_path'),target_region:text('target_region'),language_score:text('language_score'),research_exp:text('research_exp'),internship_exp:text('internship_exp'),competition_exp:text('competition_exp'),startup_exp:text('startup_exp')};setSaved(false);setError('');setBusy(true);try{const r=await fetch(apiBase+'/v1/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'保存失败，请检查填写内容');setSaved(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit} onChange={()=>setSaved(false)}><section className="form-card"><div className="account-summary"><span className="user-avatar">{initial.display_name.slice(0,1)}</span><div><h2>{initial.display_name}</h2><p>{initial.school} · {initial.major||'专业待完善'}</p></div></div><h2>基本信息</h2><div className="form-row"><label>展示昵称<input name="display_name" required maxLength={40} defaultValue={initial.display_name}/></label><label>学校<input name="school" required maxLength={120} defaultValue={initial.school}/></label></div><div className="form-row"><label>学院<input name="college" maxLength={120} defaultValue={initial.college}/></label><label>专业<input name="major" maxLength={120} defaultValue={initial.major}/></label></div><div className="form-row"><label>年级<select name="grade" defaultValue={initial.grade}>{Array.from(new Set([initial.grade,'大一','大二','大三','大四','应届生','研究生'])).filter(Boolean).map(x=><option key={x}>{x}</option>)}</select></label><label>学历<select name="degree" defaultValue={initial.degree}>{Array.from(new Set([initial.degree,'专科','本科','硕士','博士'])).filter(Boolean).map(x=><option key={x}>{x}</option>)}</select></label></div></section>
  <section className="form-card"><h2>发展目标</h2><div className="form-row"><label>目标方向<select aria-label="目标方向" name="target_path" defaultValue={initial.target_path}><option value="">尚未确定</option>{initial.target_path&&!streams.some(s=>s.code===initial.target_path)&&<option value={initial.target_path}>{initial.target_path}</option>}{streams.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label>目标年份<input name="target_year" type="number" min={2020} max={2100} defaultValue={initial.target_year??''} placeholder="例如 2027"/></label></div><div className="form-row"><label>目标地区<input name="target_region" maxLength={80} defaultValue={initial.target_region} placeholder="例如 广东、上海"/></label><label>语言成绩<input name="language_score" maxLength={80} defaultValue={initial.language_score} placeholder="例如 CET-6 520 / IELTS 6.5"/></label></div></section>
  <section className="form-card"><h2>经历与准备</h2><label>科研经历<textarea aria-label="科研经历" name="research_exp" maxLength={2000} defaultValue={initial.research_exp} placeholder="写下真实参加的研究或项目…"/></label><label>实习经历<textarea aria-label="实习经历" name="internship_exp" maxLength={2000} defaultValue={initial.internship_exp}/></label><div className="form-row"><label>竞赛经历<textarea aria-label="竞赛经历" name="competition_exp" maxLength={2000} defaultValue={initial.competition_exp}/></label><label>创业经历<textarea aria-label="创业经历" name="startup_exp" maxLength={2000} defaultValue={initial.startup_exp}/></label></div></section>
  <section className="form-card"><h2>技能与组队偏好</h2><div className="form-row"><label>兴趣（逗号分隔）<input name="interests" maxLength={300} defaultValue={initial.interests.join(',')}/></label><label>技能（逗号分隔）<input name="skills" maxLength={300} defaultValue={initial.skills.join(',')}/></label></div><label>每周可投入小时<input name="weekly_hours" type="number" min={0} max={80} defaultValue={initial.weekly_hours}/></label><label><input type="checkbox" name="discoverable" defaultChecked={initial.discoverable}/>允许同校同学通过技能匹配找到我并发起站内联系</label><p>开启后公开昵称、技能和可投入时间；学校信息由本人填写，尚未核验学籍。</p></section>
  <div className="form-footer"><button className="primary" disabled={busy}>{busy?'保存中…':'保存画像'}</button>{saved&&<p className="success" role="status">画像已保存，可立即用于资格判断。</p>}{error&&<p role="alert">{error}</p>}</div>
 </form>
}
