"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {apiBase,type Plan} from '@/lib/api';
import type {PathRecord} from '@/lib/catalog';
import {MarkdownDraft} from '@/components/markdown-draft';
import {Icon,PageHeading,EmptyState,dateLabel} from '@/components/ui';
type Result=Record<string,unknown>;
type Reply={status:string;mode?:string;message?:string;conversation_id?:string;action_id?:string;expires_at?:string;tool?:string;arguments?:{plans?:{title:string;note:string;due_date:string|null;steps?:string[]}[];markdown?:string;kind?:string;project_revision?:number;notice?:string;title?:string;status?:string;due_at?:string;note?:string};result?:Result};
type Turn={query:string;reply:Reply};
type Item={id:string|number;title:string;publication_id?:string;status?:string;deadline?:string;due_date?:string};
const choices=[['auto','自动识别'],['paths','路径咨询'],['profile','我的画像'],['search','信息查询'],['eligibility','资格核对'],['plan','生成计划'],['tasks','我的任务'],['review','进度复盘'],['startup','创业咨询'],['startup_document','创业文稿'],['update_task','更新任务'],['reminder','创建提醒'],['knowledge','原文检索'],['materials','材料建议']];
async function api(url:string,method='GET',body?:unknown){const r=await fetch(apiBase+url,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'请求失败，请检查输入或登录状态');return d;}
function ResultSummary({data}:{data:Result}){
 const paths=(data.paths||[]) as {id:number;name:string}[],refs=(data.references||[]) as {url:string;quote:string;location:string}[],rules=(data.results||[]) as {label:string;actual:string;expected:string;passed:boolean|null}[],saved=(data.plans||[]) as {id:number;title:string}[];
 const summary=data.summary as {total:number;todo:number;doing:number;done:number;overdue:number;completion_percent:number;steps_total:number;steps_done:number}|undefined;
 return <>{typeof data.workspace_url==='string'&&<Link className="button secondary" href={data.workspace_url}>打开创业工作台 →</Link>}{Array.isArray(data.startup_projects)&&<div className="agent-result-card"><h4>我的创业项目</h4>{(data.startup_projects as {id:string;name:string}[]).map(p=><p key={p.id}><Link href={'/startup?project='+p.id}>{p.name}</Link></p>)}</div>}{data.startup_document&&typeof data.startup_document==='object'?<p>创业文稿已保存为 v{String((data.startup_document as {version:number}).version)}，可在工作台继续编辑和下载。</p>:null}{typeof data.model_notice==='string'&&<p className="field-hint" role="status">{data.model_notice}</p>}{summary&&<div className="agent-result-card"><h4>个人执行进度 · {summary.completion_percent}%</h4><p>共 {summary.total} 项 · 待开始 {summary.todo} · 进行中 {summary.doing} · 已完成 {summary.done}</p><p>逾期 {summary.overdue} 项 · 准备清单 {summary.steps_done}/{summary.steps_total}</p><Link href="/tracker">管理计划与清单 →</Link></div>}{typeof data.model_explanation==='string'&&<p style={{whiteSpace:'pre-wrap'}}>{data.model_explanation}</p>}{paths.length>0&&<div className="tagrow">{paths.map(p=><span key={p.id}>{p.name}</span>)}</div>}{Array.isArray(data.suggestions)&&<ul>{(data.suggestions as string[]).map((s,i)=><li key={i}>{s}</li>)}</ul>}{'eligible' in data&&<p className="badge">条件核对：{data.eligible===true?'已核对的规则符合':data.eligible===false?'存在不符合的规则':'信息不足，不能确定'}</p>}{rules.map((r,i)=><div className="agent-result-card" key={i}><h4>{r.label} · {r.passed===true?'符合':r.passed===false?'不符合':'待补充或核验'}</h4><p>当前：{r.actual||'未填写'} · 要求：{r.expected}</p></div>)}{refs.map((r,i)=><blockquote key={i}>{r.quote}<p><a href={r.url} target="_blank" rel="noreferrer">核对原文</a> · {r.location}</p></blockquote>)}{saved.length>0&&<div className="agent-result-card"><h4>已保存 {saved.length} 项计划</h4>{saved.map(p=><p key={p.id}>✓ {p.title}</p>)}<Link href="/tracker">去我的计划查看 →</Link></div>}{typeof data.display_name==='string'&&<div className="agent-result-card"><h4>{data.display_name}的个人画像</h4><p>{String(data.school||'学校待填写')} · {String(data.major||'专业待填写')} · {String(data.grade||'年级待填写')}</p><p>目标：{String(data.target_path||'尚未确定')}</p><Link href="/profile">完善个人资料 →</Link></div>}{typeof data.reminder_id==='string'&&<Link className="button secondary" href="/notifications">查看已保存的提醒</Link>}{typeof data.source==='string'&&<p className="muted">依据：{data.source}</p>}{typeof data.message==='string'&&<p>{data.message}</p>}</>;
}
export default function Agent(){
 const [query,setQuery]=useState(''),[intent,setIntent]=useState('auto'),[cid,setCid]=useState<string>(),[turns,setTurns]=useState<Turn[]>([]),[sessions,setSessions]=useState<{id:string;title:string}[]>([]),[paths,setPaths]=useState<PathRecord[]>([]),[plans,setPlans]=useState<Plan[]>([]);
 const [path,setPath]=useState(''),[keyword,setKeyword]=useState(''),[region,setRegion]=useState(''),[pub,setPub]=useState(''),[item,setItem]=useState(''),[selectedTitle,setSelectedTitle]=useState(''),[plan,setPlan]=useState(''),[status,setStatus]=useState('doing'),[due,setDue]=useState('');
 const [startupId,setStartupId]=useState(''),[startupProjects,setStartupProjects]=useState<{id:string;name:string}[]>([]),[documentKinds,setDocumentKinds]=useState<{kind:string;title:string}[]>([]),[docKind,setDocKind]=useState('');
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mode,setMode]=useState('');const input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null);
 const [moreSessions,setMoreSessions]=useState(false);
 async function refresh(){const rows=await api('/v1/development-agent/conversations');setSessions(rows);setMoreSessions(rows.length===30);}
 async function loadSessions(){setBusy(true);setError('');try{const rows=await api('/v1/development-agent/conversations?offset='+sessions.length);setSessions(old=>[...old,...rows]);setMoreSessions(rows.length===30)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let alive=true;const q=new URLSearchParams(window.location.search);if(choices.some(([v])=>v===q.get('intent')))setIntent(q.get('intent')!);setPath(q.get('path')||'');setStartupId(q.get('startup_project_id')||'');if(q.get('intent')==='startup')setQuery('围绕这个项目给我创业建议');setPlan(q.get('plan_id')||'');setPub(q.get('publication_id')||'');setItem(q.get('item_id')||'');if(q.get('intent')==='plan')setQuery('请为我制定这个方向的准备计划');if(q.get('intent')==='reminder')setQuery('为这项计划设置提醒');if(q.get('intent')==='eligibility')setQuery('请核对我是否符合这个事项的申请条件');Promise.all([api('/v1/paths'),api('/v1/development-agent/status'),api('/v1/development-agent/conversations'),api('/v1/plans'),api('/v1/startup/projects'),api('/v1/startup/capabilities')]).then(([p,s,c,t,sp,sc])=>{if(alive){setPaths(p);setMode(s.mode);setSessions(c);setMoreSessions(c.length===30);setPlans(t);setStartupProjects(sp);setDocumentKinds(sc.document_kinds)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[turns,busy]);
 function preset(nextIntent:string,text:string){setIntent(nextIntent);setQuery(text);input.current?.focus()}
 function reset(){setCid(undefined);setTurns([]);setPub('');setItem('');setSelectedTitle('');setPlan('');setQuery('');setIntent('auto');setPath('');setKeyword('');setRegion('');setStatus('doing');setDue('');setStartupId('');setDocKind('');setError('')}
 async function send(e:FormEvent){e.preventDefault();if(busy||!query.trim())return;if(intent==='eligibility'&&(!pub||!item)){setError('请先查询信息，在结果中选择“核对资格”。');return}if(['update_task','reminder'].includes(intent)&&!plan){setError('请先选择一项个人计划。');return}if(intent==='reminder'&&!due){setError('请设置提醒时间。');return}setBusy(true);setError('');const text=query;try{const reply=await api('/v1/development-agent/chat','POST',{query:text,intent,conversation_id:cid,keyword:intent==='search'?keyword:'',path_code:path||null,region:region||null,publication_id:pub||null,item_id:item||null,plan_id:plan?Number(plan):null,startup_project_id:startupId||null,document_kind:docKind||null,status,due_at:due?new Date(due).toISOString():null});setCid(reply.conversation_id);setTurns(t=>[...t,{query:text,reply}]);setQuery('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function choose(id:string){setBusy(true);setError('');try{setTurns(await api('/v1/development-agent/conversations/'+id));setCid(id);setPath('');setKeyword('');setRegion('');setDue('');setQuery('');setPub('');setItem('');setStartupId('');setDocKind('');setSelectedTitle('');setPlan('');setIntent('auto')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function action(index:number,op:string){setBusy(true);setError('');try{const reply=await api('/v1/development-agent/actions/'+turns[index].reply.action_id+'/'+op,'POST',{});setTurns(t=>t.map((x,i)=>i===index?{...x,reply:{...x.reply,...reply}}:x));if(op==='confirm')setPlans(await api('/v1/plans'))}catch(e){setError((e as Error).message);if(cid){try{setTurns(await api('/v1/development-agent/conversations/'+cid))}catch{/* keep visible conversation */}}}finally{setBusy(false)}}
 async function remove(){if(!cid||!window.confirm('删除这段会话？已保存的业务计划保留，未确认的操作取消。'))return;setBusy(true);setError('');try{await api('/v1/development-agent/conversations/'+cid,'DELETE');reset();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="shell"><PageHeading eyebrow="YOUR DEVELOPMENT ASSISTANT" title="和校伴，一起想清楚下一步" description="了解方向、寻找信息、核对条件，或围绕创业项目设计商业与文稿。"><Link className="button secondary" href="/startup">创业工作台</Link><Link className="button secondary" href="/tracker"><Icon name="check" size={15}/>我的计划</Link></PageHeading>
  <div className="agent-workspace"><aside className="agent-sessions" aria-label="助手会话"><button disabled={busy} onClick={reset}><Icon name="plus" size={14}/>新会话</button><h2>最近会话</h2>{loading&&<small className="muted">正在读取…</small>}{sessions.map(s=><button key={s.id} className={'session-button '+(s.id===cid?'active':'')} title={s.title} disabled={busy} onClick={()=>void choose(s.id)}>{s.title}</button>)}{moreSessions&&<button disabled={busy} onClick={()=>void loadSessions()}>加载更多会话</button>}{!loading&&!sessions.length&&<p className="field-hint">你的对话会保存在这里。</p>}</aside>
   <section className="agent-main"><div className="agent-chathead"><span className="feed-icon green"><Icon name="spark" size={18}/></span><b>校伴 Agent</b><span className={'badge '+(mode==='dify'?'green':'')}>{loading?'读取状态中':mode==='dify'?'模型服务已配置':'规则助手'}</span>{cid&&<button className="quiet" disabled={busy} onClick={remove} aria-label="删除当前会话"><Icon name="close" size={14}/></button>}</div>
    <div className="agent-turns" aria-label="助手对话记录" aria-live="polite">{!turns.length&&<div className="agent-welcome"><span className="feed-icon green"><Icon name="spark" size={25}/></span><h2>你想从哪里开始？</h2><p>{mode==='dify'?'校伴会查询平台信息，并结合结果提供解释。':'当前使用规则助手，可查询真实业务记录并生成基础准备计划。'}</p><div className="suggestion-grid"><button onClick={()=>preset('paths','我想了解适合大学生的发展方向')}><Icon name="book" size={16}/>了解发展方向</button><button onClick={()=>preset('plan','请帮我制定考研准备计划')}><Icon name="check" size={16}/>制定准备计划</button><button onClick={()=>preset('search','招聘')}><Icon name="search" size={16}/>寻找公开信息</button><button onClick={()=>preset('review','复盘我的执行进度，下一步做什么')}><Icon name="calendar" size={16}/>复盘执行进度</button></div></div>}
     {turns.map((t,i)=><div key={i}><div className="conversation-question"><span className="user-avatar">我</span><p>{t.query}</p></div><div className="assistant-answer"><span className="feed-icon green"><Icon name="spark" size={16}/></span><div><h3>校伴 Agent <span className="badge">{choices.find(([v])=>v===t.reply.tool)?.[1]||'助手'}</span></h3><p>{t.reply.message}</p>
      {t.reply.status==='confirmation_required'&&t.reply.arguments&&<div className="agent-result-card"><span className="badge amber">等待你确认</span>{t.reply.arguments.plans?.map((p,j)=><div key={j}><h4>{j+1}. {p.title}</h4><p style={{whiteSpace:'pre-wrap'}}>{p.note}</p>{p.steps&&<ul>{p.steps.map((step,k)=><li key={k}>{step}</li>)}</ul>}</div>)}{t.reply.arguments.markdown&&<details className="agent-document-preview" open><summary>文稿预览 · 项目资料 v{t.reply.arguments.project_revision}</summary><MarkdownDraft text={t.reply.arguments.markdown}/><p className="field-hint">{t.reply.arguments.notice}</p></details>}{t.reply.arguments.title&&<h4>{t.reply.arguments.title}</h4>}{t.reply.arguments.status&&<p>更新为：{({todo:'待开始',doing:'进行中',done:'已完成'} as Record<string,string>)[t.reply.arguments.status]}</p>}{t.reply.arguments.due_at&&<p>提醒时间：{new Date(t.reply.arguments.due_at).toLocaleString('zh-CN')}</p>}<div className="button-row"><button className="primary" disabled={busy} onClick={()=>void action(i,'confirm')}>确认保存</button><button disabled={busy} onClick={()=>void action(i,'cancel')}>取消</button><small className="muted">{t.reply.expires_at?'有效至 '+new Date(t.reply.expires_at).toLocaleTimeString('zh-CN'):'10 分钟内有效'}</small></div></div>}
      {t.reply.result&&<>{((t.reply.result.items as Item[]|undefined)||[]).map(x=><div className="agent-result-card" key={x.id}><h4>{x.title}</h4><p>{x.deadline?'截止 '+dateLabel(x.deadline):x.due_date?'个人计划日期 '+dateLabel(x.due_date):x.status?({todo:'待开始',doing:'进行中',done:'已完成'} as Record<string,string>)[x.status]||x.status:''}</p><div className="button-row">{x.publication_id?<><Link className="button secondary" href={'/data/'+x.publication_id}>详情与来源</Link><button disabled={busy} onClick={()=>{setPub(x.publication_id!);setItem(String(x.id));setSelectedTitle(x.title);preset('eligibility','请核对我是否符合这个事项的条件')}}>核对资格</button></>:<><Link className="button secondary" href="/tracker">查看计划</Link><button disabled={busy} onClick={()=>{setPlan(String(x.id));preset('reminder','为这项计划设置提醒')}}>设置提醒</button><button disabled={busy} onClick={()=>{setPlan(String(x.id));preset('update_task','更新这项计划的进度')}}>更新进度</button></>}</div></div>)}{Array.isArray(t.reply.result.items)&&!t.reply.result.items.length&&<EmptyState title="暂无匹配记录" description="可以调整关键词或先创建一项计划。"/>}<ResultSummary data={t.reply.result}/></>}
      {t.reply.status==='cancelled'&&<p>操作已取消，未保存。</p>}{t.reply.status==='expired'&&<p>预览已过期，请重新提出需求。</p>}
     </div></div></div>)}{busy&&<p className="field-hint">校伴正在处理，请稍候…</p>}<div ref={bottom}/></div>
    <form className="agent-composer" onSubmit={send}><div className="chat-compose-box"><div className="agent-compose-options"><select aria-label="助手功能" disabled={busy} value={intent} onChange={e=>setIntent(e.target.value)}>{choices.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><select aria-label="助手发展路径" disabled={busy} value={path} onChange={e=>setPath(e.target.value)}><option value="">自动识别方向</option>{paths.filter(p=>p.code).map(p=><option key={p.id} value={p.code!}>{p.name}</option>)}</select></div>
     <div className="agent-parameters">{['startup','startup_document','auto'].includes(intent)&&<div className="form-row"><label>创业项目（可选）<select aria-label="创业项目（可选）" disabled={busy} value={startupId} onChange={e=>setStartupId(e.target.value)}><option value="">选择项目，或先咨询创业流程</option>{startupProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{intent==='startup_document'&&<label>创业文稿类型<select aria-label="创业文稿类型" disabled={busy} value={docKind} onChange={e=>setDocKind(e.target.value)}><option value="">从消息自动识别</option>{documentKinds.map(k=><option key={k.kind} value={k.kind}>{k.title}</option>)}</select></label>}</div>}{intent==='search'&&<div className="form-row"><label>查询关键词<input value={keyword} placeholder="留空使用消息内容" maxLength={100} onChange={e=>setKeyword(e.target.value)}/></label><label>地区<input value={region} placeholder="不限，如 CN-GD" maxLength={80} onChange={e=>setRegion(e.target.value)}/></label></div>}{intent==='eligibility'&&<p className="field-hint">{pub&&item?`已选择：${selectedTitle||'来源事项'}`:'先查询信息，在结果卡片中点击“核对资格”。'}</p>}{['update_task','reminder'].includes(intent)&&<div className="form-row"><label>选择我的计划<select required value={plan} onChange={e=>setPlan(e.target.value)}><option value="">请选择计划</option>{plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{intent==='update_task'?<label>目标状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todo">待开始</option><option value="doing">进行中</option><option value="done">已完成</option></select></label>:<label>提醒时间（本地时间）<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>}</div>}</div>
     <textarea ref={input} aria-label="给校伴的消息" disabled={busy} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} required maxLength={6000} value={query} onChange={e=>setQuery(e.target.value)} placeholder="告诉校伴你想做什么，或粘贴需要建议的材料片段…"/>
     <div className="composer-tools"><span>Ctrl / ⌘ + Enter 发送；保存前确认。</span><button className="primary" disabled={busy||loading||!query.trim()}>{busy?'处理中…':'发送'}<Icon name="send" size={13}/></button></div></div>{error&&<p role="alert">{error}</p>}</form>
   </section></div>
 </div>
}
