"use client";
import {useState,useEffect} from "react";
import {TeamTaskBoard} from "@/components/team-task-board";
import {apiBase} from "@/lib/api";
import Link from "next/link";
import {PageHeading,Icon,TopicBar} from "@/components/ui";
type Team={id:string;title:string;members:string[];room_id:string;owner:string;capacity:number;is_owner:boolean};
type Invite={team_id:string;status:string;title:string;team_status:string};
export default function Manager(){
 const [teams,setTeams]=useState<Team[]>([]),[invites,setInvites]=useState<Invite[]>([]),[status,setStatus]=useState(""),[myId,setMyId]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function call(path:string,data?:unknown){const r=await fetch(apiBase+path,data===undefined?{cache:"no-store"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok){const err=await r.json();throw new Error(typeof err.detail==="string"?err.detail:"输入无效或操作失败")}return r.json()}
 async function refresh(){setTeams(await call("/v1/teams"));setInvites(await call("/v1/invitations"))}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);try{setStatus("");await fn();await refresh()}catch(e){setStatus(String(e))}finally{setBusy(false)}}
 useEffect(()=>{call("/v1/profile").then(p=>setMyId(p.user_id)).catch(()=>{});refresh().catch(()=>setStatus("请登录后读取团队")).finally(()=>setLoading(false))},[]);
 return <div className="shell team-manager"><PageHeading eyebrow="MY TEAMS" title="团队管理" description="团队由队长组织，任务由负责人推进。邀请、讨论与协作进度清楚可见。"><Link className="button secondary" href="/teams"><Icon name="users" size={15}/>进入交流空间</Link></PageHeading>{loading&&<p role="status">正在加载团队…</p>}<fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><form className="form-card create-team-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await call("/v1/teams",{title:f.get("title"),capacity:Number(f.get("capacity"))})})}}><label>新队伍名称<input name="title" required maxLength={100}/></label><label>人数上限（含队长）<input name="capacity" type="number" min={2} max={20} defaultValue={5} required/></label><button>创建队伍</button></form>
 <h2>收到的邀请</h2>{!loading&&!invites.length&&<p>暂无邀请。</p>}{invites.map(i=><article className="card" key={i.team_id}><p>队伍 {i.title} · {i.status}</p>{i.status==="pending"&&i.team_status==="active"&&<div>{["accept","reject"].map(action=><button key={action} onClick={()=>run(async()=>{await call(`/v1/invitations/${i.team_id}/decision`,{action})})}>{action==="accept"?"接受":"拒绝"}</button>)}</div>}</article>)}
 <div className="section-title"><h2>我的队伍</h2><span className="badge">{teams.length} 个团队</span></div>{!loading&&!teams.length&&<p>暂无队伍，可创建队伍或接受邀请。</p>}<div className="team-cards">{teams.map(t=><article className="card" id={`team-${t.id}`} key={t.id}><h3>{t.title}</h3><p>{t.members.length} / {t.capacity} 位成员</p>{t.is_owner&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await call(`/v1/teams/${t.id}/invitations`,{target:f.get("target")});setStatus("邀请已发送")})}}><label>成员用户 ID<input name="target" required maxLength={80}/></label><button>邀请成员</button></form>}<ul>{t.members.map(m=><li key={m}>{m}{m===t.owner?"（队长）":t.is_owner&&<button onClick={()=>{if(window.confirm("确认移除此成员？"))run(async()=>{await call(`/v1/teams/${t.id}/remove`,{target:m})})}}>移除</button>}</li>)}</ul><TeamTaskBoard teamId={t.id} members={t.members} owner={t.is_owner} myId={myId}/><a href={`/teams?room=${encodeURIComponent(t.room_id)}`}>进入队伍房间</a><p><button className="danger" onClick={()=>{if(window.confirm(t.is_owner?"解散后所有成员将失去房间访问权，确认解散？":"确认退出队伍？"))run(async()=>{await call(`/v1/teams/${t.id}/${t.is_owner?"dissolve":"leave"}`,{})})}}>{t.is_owner?"解散队伍":"退出队伍"}</button></p></article>)}</div></fieldset><p role="status">{status}</p></div>
}
