"""Build a self-contained gallery of actual Stage33 screenshots."""
from pathlib import Path
import base64
import json
root=Path(__file__).resolve().parents[1]
folder=root/'artifacts/stage33'
entries=[('student-desktop','学生工作台','普通用户：发展信息、个人计划与协作入口。没有运营管理导航。'),('information-desktop','发展信息','按发展频道组织，筛选、查看证据并加入个人计划。'),('plans-desktop','个人计划','待开始、进行中、已完成；保存进度并设置提醒。'),('agent-desktop','校伴 Agent','私有会话、工具查询和确认后写入。当前截图为规则模式。'),('conversations-desktop','交流空间','按真实房间组织交流；匹配队友和管理团队。'),('admin-desktop','运营后台','管理员专属工作空间：来源、导入、审核、举报与审计。'),('workspace-mobile','手机工作台','响应式内容布局，保留完整业务入口。'),('navigation-mobile','手机导航','抽屉式导航，包含发展频道、个人功能与明确身份。')]
images=[]
for name,title,description in entries:
    image='data:image/png;base64,'+base64.b64encode((folder/(name+'.png')).read_bytes()).decode()
    images.append(dict(name=name,title=title,description=description,image=image))
font='data:font/woff;base64,'+base64.b64encode((root/'frontend/public/fonts/campus-sans-regular.woff').read_bytes()).decode()
html='''<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CampusMate Stage33 · 界面预览</title><style>
@font-face{font-family:Campus;src:url(FONT) format('woff')}*{box-sizing:border-box}body{margin:0;background:#edf2f6;color:#344c5d;font:14px Campus,system-ui,sans-serif}header{padding:25px 32px;background:#3d5261;color:white;display:flex;align-items:center;justify-content:space-between;gap:20px}h1{font-size:20px;margin:0 0 8px}header p{font-size:12px;color:#c8d8e3;margin:0}header span{border:1px solid #ffffff40;padding:6px 11px;border-radius:5px;font-size:11px;white-space:nowrap}nav{position:sticky;top:0;z-index:2;background:#f8fafcee;border-bottom:1px solid #d6e1e9;display:flex;gap:8px;padding:14px 30px;overflow:auto;backdrop-filter:blur(12px)}button{font:inherit;border:1px solid transparent;background:transparent;color:#718796;cursor:pointer;white-space:nowrap;padding:9px 13px;border-radius:5px;font-size:12px}button[aria-selected=true]{background:#dcecf7;color:#367da8;border-color:#c3dcea}button:focus-visible{outline:3px solid #8bbede}main{max-width:1540px;padding:26px 30px 45px;margin:auto}.caption{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:20px}.caption h2{margin:0 0 5px;font-size:17px}.caption p{margin:0;font-size:12px;color:#7d93a2}.caption span{font-size:11px;color:#8ba0ad}.frame{border:1px solid #d6e1e8;border-radius:10px;box-shadow:0 9px 40px #243c5010;background:#fff;overflow:hidden;margin:auto}.frame img{display:block;width:100%;height:auto}.frame.mobile{max-width:390px}footer{font-size:11px;color:#8296a4;text-align:center;margin:30px auto 0;max-width:750px;line-height:1.9}@media(max-width:700px){header{padding:20px;display:block}header span{display:inline-block;margin-top:13px}nav{padding:10px 15px}main{padding:20px 12px}.caption{display:block}.caption span{display:block;margin-top:8px}header h1{font-size:18px}}
</style></head><body><header><div><h1>CampusMate · 校伴工作空间</h1><p>Stage33 / Zulip Campus 风格 · 学生与管理员独立工作界面</p></div><span>实际项目运行截图</span></header><nav role="tablist" aria-label="界面预览"></nav><main><div class="caption"><div><h2 id="title"></h2><p id="description"></p></div><span id="size"></span></div><div class="frame" id="frame" role="tabpanel"><img id="screen" alt=""></div><footer>此文件用于离线查看界面，是实际运行截图的预览合集。完整操作需启动源码项目。截图含明确标记的模拟数据，不代表真实运营人数；原始业务记录与清理层次见随附实现报告。</footer></main><script>
const screens=DATA;const nav=document.querySelector('nav');screens.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s.title;b.setAttribute('role','tab');b.onclick=()=>show(i);nav.append(b)});
function show(i){const s=screens[i];document.getElementById('title').textContent=s.title;document.getElementById('description').textContent=s.description;const img=document.getElementById('screen');img.src=s.image;img.alt=s.title+'实际运行截图';const mobile=s.name.includes('mobile');document.getElementById('frame').className='frame'+(mobile?' mobile':'');document.getElementById('size').textContent=mobile?'手机端 / 390 px':'桌面端 / 1440 px';[...nav.children].forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j))});}show(0);
</script></body></html>'''
html=html.replace('FONT',font).replace('DATA',json.dumps(images,ensure_ascii=False))
output=folder/'CampusMate_Stage33_UI_Preview.html';output.write_text(html);print(output)
