import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

test('创业工作台：项目、财务股权、BP版本、Agent和流程',async({page,request},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/startup');
 await page.getByRole('button',{name:'新建创业项目',exact:true}).click();
 const name='创业验收-'+Date.now();
 await page.getByLabel('项目名称',{exact:true}).fill(name);
 await page.getByLabel('项目一句话与目标',{exact:true}).fill('为小团队提供客户访谈及付费验证工具');
 await page.getByLabel('已有验证与运营数据',{exact:true}).fill('已访谈3位潜在客户，暂无付费订单');
 await page.getByRole('button',{name:'保存项目资料',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('项目资料已保存');
 await page.getByRole('button',{name:'商业设计',exact:true}).click();
 await page.getByLabel('客户细分',{exact:true}).fill('小团队负责人');
 await page.getByLabel('客户痛点',{exact:true}).fill('无法有效追踪付费实验');
 await page.getByLabel('价值主张与解决方案',{exact:true}).fill('记录访谈、订单与验证结果');
 await page.getByRole('button',{name:'保存项目资料',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('项目资料已保存');
 await page.getByRole('button',{name:'财务与股权',exact:true}).click();
 for(const [label,value] of [['单价','100'],['月销量 / 付费单位','100'],['单位变动成本','40'],['月固定支出','9000'],['可用现金','18000'],['本轮投前估值','1000000'],['本轮新增投资','250000'],['本轮新增期权池 %（投前）','10']])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByRole('button',{name:'添加股东',exact:true}).click();
 await page.getByLabel('股东 1 名称',{exact:true}).fill('核心创始人');
 await page.getByRole('button',{name:'保存并测算',exact:true}).click();
 await expect(page.getByRole('heading',{name:/测算结果/})).toBeVisible();
 await expect(page.locator('.startup-metrics').filter({hasText:'资金可维持月数'})).toContainText('6');
 await expect(page.getByRole('cell',{name:'72',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const qa=path.resolve('../.test-runtime');fs.mkdirSync(qa,{recursive:true});
 await page.evaluate(async()=>{await document.fonts.ready;document.documentElement.style.scrollBehavior="auto";window.scrollTo({top:0,behavior:'instant'})});
 await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);
 await page.screenshot({path:path.join(qa,'startup-'+testInfo.project.name+'.png'),fullPage:true});
 await page.getByRole('button',{name:'文稿中心',exact:true}).click();
 await page.getByLabel('文稿类型',{exact:true}).selectOption('bp');
 await page.getByRole('button',{name:'生成草稿',exact:true}).click();
 await expect(page.getByRole('article',{name:'创业文稿预览'})).toContainText('暂无付费订单');
 await expect(page.getByRole('article',{name:'创业文稿预览'})).toContainText('市场规模【待核验】');
 await page.getByRole('button',{name:'保存文稿版本',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('v1');
 await page.getByRole('button',{name:'编辑文稿',exact:true}).click();
 await page.getByLabel('编辑创业文稿').fill((await page.getByLabel('编辑创业文稿').inputValue())+'\n\n## 验收修改\n\n新增真实验证计划。');
 await page.getByRole('button',{name:'保存文稿版本',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('v2');
 const downloadPromise=page.waitForEvent('download');
 await page.locator('.startup-doc-history').getByRole('link',{name:'下载',exact:true}).first().click();
 const downloaded=await downloadPromise;expect(downloaded.suggestedFilename()).toBe('bp-v2.md');
 await page.getByRole('button',{name:'创业流程',exact:true}).click();
 await expect(page.locator('.startup-step')).toHaveCount(10);
 await page.getByLabel('已完成自评').first().check();
 await page.getByRole('button',{name:'保存项目资料',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('项目资料已保存');
 const projects=await(await request.get('/api/backend/v1/startup/projects')).json();
 const id=projects.find((p:{name:string})=>p.name===name).id;
 await page.goto('/startup?project='+id);
 await page.getByRole('button',{name:'创业流程',exact:true}).click();
 await expect(page.getByLabel('已完成自评').first()).toBeChecked();
 await page.getByRole('link',{name:'与校伴讨论',exact:true}).click();
 await expect(page.getByLabel('创业项目（可选）')).toHaveValue(id);
 await page.getByLabel('助手功能').selectOption('startup_document');
 await page.getByLabel('创业文稿类型').selectOption('user_agreement');
 await page.getByLabel('给校伴的消息').fill('请起草用户协议');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await expect(page.getByText('等待你确认')).toBeVisible();
 await expect(page.getByText('文稿预览 · 项目资料',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'确认保存',exact:true}).click();
 await expect(page.getByText('创业文稿已保存为 v1',{exact:false})).toBeVisible();
 expect(errors).toEqual([]);
});
