"""baseline_v070"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('expected', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_rules_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('message_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.String(length=80), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('organization', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_type'), ['type'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('school', sa.String(length=120), nullable=False),
    sa.Column('college', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('major', sa.String(length=120), nullable=False),
    sa.Column('interests', sa.String(length=300), nullable=False),
    sa.Column('skills', sa.String(length=300), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', 'due_at')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extracted_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_status'), ['status'], unique=False)

    op.create_table('room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_messages_room_id'), ['room_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_blocks',
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'target')
    )
    op.create_table('team_invitations',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('team_id', 'target')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_table('tracker_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('opportunity_id', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id')
    )
    with op.batch_alter_table('tracker_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracker_items_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracker_items_opportunity_id'))

    op.drop_table('tracker_items')
    op.drop_table('teams')
    op.drop_table('team_invitations')
    op.drop_table('social_blocks')
    op.drop_table('rooms')
    with op.batch_alter_table('room_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_messages_room_id'))

    op.drop_table('room_messages')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_status'))

    op.drop_table('review_items')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))

    op.drop_table('reminders')
    op.drop_table('profiles')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_title'))
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_deadline'))

    op.drop_table('opportunities')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('message_reports')
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_rules_opportunity_id'))

    op.drop_table('eligibility_rules')
    # ### end Alembic commands ###
