"""real_matching_team_lifecycle"""
from alembic import op
import sqlalchemy as sa

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=40), server_default='同学', nullable=False))
        batch_op.add_column(sa.Column('discoverable', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default='5', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('discoverable')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
