"use client";
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {apiBase} from '@/lib/api';
import {Icon,PageHeading,EmptyState} from '@/components/ui';
import {MarkdownDraft} from '@/components/markdown-draft';
import './startup.css';

type Founder={name:string;role:string;percent:string|number;contribution:string};
type Finance=Record<string,string|number|null>;
type Brief=Record<string,unknown>&{name:string;stage:string;jurisdiction:string;founders:Founder[];finance:Finance;completed_steps:string[]};
type Project={id:string;brief:Brief;revision:number};
type Listed={id:string;name:string;stage:string;revision:number};
type Source={title:string;url:string;scope:string};
type Step={id:string;title:string;kind:string;tasks:string[];done?:boolean};
type Capabilities={document_kinds:{kind:string;title:string}[];roadmap:Step[];fields:{group:string;name:string;label:string}[];sources:Source[]};
type Draft={kind:string;title:string;markdown:string;sources:Source[];project_revision:number;expected_document_version:number;mode:string;model_notice?:string;notice?:string};
type Document={id:string;title:string;kind:string;version:number;project_revision:number;created_at:string};
type Analysis={project_revision:number;progress_percent:number;roadmap:Step[];economics:{missing_fields:string[];monthly_revenue?:number;monthly_operating_result?:number;monthly_burn?:number;unit_contribution?:number;contribution_margin_pct?:number|null;break_even_units?:number|null;runway_months?:number|null;runway_note?:string;assumptions:string[];projections?:{scenario:string;year:number;revenue:number;cost:number;operating_result:number}[]};cap_table:{rows:{name:string;before_pct:number;after_pct:number;role:string}[];assumptions:string[];missing_fields?:string[]}};
const tabs=[['overview','项目概况'],['business','商业设计'],['finance','财务与股权'],['documents','文稿中心'],['roadmap','创业流程']];
const financeFields=[['price','单价'],['monthly_units','月销量 / 付费单位'],['variable_cost','单位变动成本'],['fixed_cost','月固定支出'],['cash','可用现金'],['annual_volume_growth_pct','年销量增长假设 %'],['annual_cost_growth_pct','年固定成本增长假设 %'],['pre_money','本轮投前估值'],['investment','本轮新增投资'],['new_pool_pct','本轮新增期权池 %（投前）']];
const stages:Record<string,string>={idea:'想法与验证',mvp:'MVP / 初步客户',growth:'成长与融资',scale:'规模化 / 资本化'};
function empty():Brief{return {name:'',stage:'idea',jurisdiction:'CN',founders:[],finance:{price:null,monthly_units:null,variable_cost:null,fixed_cost:null,cash:null,annual_volume_growth_pct:0,annual_cost_growth_pct:0,pre_money:null,investment:null,new_pool_pct:0},completed_steps:[]}}
async function api(path:string,method='GET',body?:unknown){const response=await fetch(apiBase+path,{method,headers:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'资料格式不正确，请检查名称、数值与股权合计');return data;}
const num=(value:number|null|undefined)=>value==null?'待计算':value.toLocaleString('zh-CN',{maximumFractionDigits:2});

export default function Startup(){
 const [cap,setCap]=useState<Capabilities>(),[projects,setProjects]=useState<Listed[]>([]),[project,setProject]=useState<Project>(),[brief,setBrief]=useState<Brief>(empty),[tab,setTab]=useState('overview'),[dirty,setDirty]=useState(false);
 const [analysis,setAnalysis]=useState<Analysis>(),[documents,setDocuments]=useState<Document[]>([]),[draft,setDraft]=useState<Draft>(),[kind,setKind]=useState('bp'),[instruction,setInstruction]=useState(''),[modelAssist,setModelAssist]=useState(false),[edit,setEdit]=useState(false),[docEdited,setDocEdited]=useState(false),[moreDocs,setMoreDocs]=useState(false);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(id:string){const [p,a,d]=await Promise.all([api('/v1/startup/projects/'+id),api('/v1/startup/projects/'+id+'/analysis'),api('/v1/startup/projects/'+id+'/documents')]);setProject(p);setBrief(p.brief);setAnalysis(a);setDocuments(d);setMoreDocs(d.length===100);setDraft(undefined);setDirty(false);setDocEdited(false);setError('');setMessage('')}
 useEffect(()=>{let alive=true;Promise.all([api('/v1/startup/capabilities'),api('/v1/startup/projects')]).then(async([c,ps])=>{if(!alive)return;setCap(c);setProjects(ps);const q=new URLSearchParams(window.location.search);const id=q.get('project');if(q.get('kind')&&c.document_kinds.some((k:{kind:string})=>k.kind===q.get('kind'))){setKind(q.get('kind')!);setTab('documents')}if(id&&ps.some((p:Listed)=>p.id===id))await load(id);else if(ps.length)await load(ps[0].id)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 const modify=(key:string,value:unknown)=>{setBrief(b=>({...b,[key]:value}));setDirty(true);setMessage('')};
 async function save(){if(!brief.name.trim())throw Error('请先填写项目名称');const saved=await api('/v1/startup/projects'+(project?'/'+project.id:''),project?'PUT':'POST',{...brief,...(project?{expected_revision:project.revision}:{})});setProject(saved);setBrief(saved.brief);setDirty(false);setProjects(await api('/v1/startup/projects'));return saved as Project}
 async function perform(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveForm(e:FormEvent){e.preventDefault();await perform(async()=>{const p=await save();setAnalysis(await api('/v1/startup/projects/'+p.id+'/analysis'));setMessage('项目资料已保存')})}
 function abandon():boolean{return !((dirty||docEdited)&&!window.confirm('有未保存的资料或文稿，仍要切换吗？'))}
 function newProject(){if(!abandon())return;setProject(undefined);setBrief(empty());setAnalysis(undefined);setDocuments([]);setMoreDocs(false);setDraft(undefined);setTab('overview');setDirty(false);setDocEdited(false);setError('');setMessage('')}
 async function generate(nextKind=kind){await perform(async()=>{if(docEdited&&!window.confirm('重新生成会替换尚未保存的文稿，继续吗？'))return;const p=dirty||!project?await save():project;const d=await api('/v1/startup/projects/'+p.id+'/draft','POST',{kind:nextKind,expected_revision:p.revision,instruction,model_assist:modelAssist});setDraft(d);setKind(nextKind);setDocEdited(false);setEdit(false);setTab('documents');setMessage('草稿已生成，可编辑后保存版本')})}
 async function saveDraft(){if(!project||!draft)return;await perform(async()=>{const saved=await api('/v1/startup/projects/'+project.id+'/documents','POST',{kind:draft.kind,expected_revision:draft.project_revision,expected_document_version:draft.expected_document_version,markdown:draft.markdown});setDraft({...draft,expected_document_version:saved.version});setDocEdited(false);const docs=await api('/v1/startup/projects/'+project.id+'/documents');setDocuments(docs);setMoreDocs(docs.length===100);setMessage('文稿已保存为 v'+saved.version)})}
 async function openDoc(doc:Document){if(!project||!abandon())return;await perform(async()=>{const data=await api('/v1/startup/projects/'+project.id+'/documents/'+doc.id);const latest=await api('/v1/startup/projects/'+project.id+'/documents');const version=Math.max(...latest.filter((d:Document)=>d.kind===doc.kind).map((d:Document)=>d.version),0);setDraft({...data,project_revision:project.revision,expected_document_version:version,mode:'saved_version'});setKind(doc.kind);setEdit(false);setDocEdited(false);setTab('documents');setMessage('正在查看 v'+doc.version+'；按资料版本 '+doc.project_revision+' 起草。保存修改将创建新版本。')})}
 async function remove(){if(!project||!window.confirm('删除此创业项目及全部文稿版本？此操作不能撤销。'))return;await perform(async()=>{await api('/v1/startup/projects/'+project.id,'DELETE');setDirty(false);setDocEdited(false);setProject(undefined);setBrief(empty());setAnalysis(undefined);setDocuments([]);setDraft(undefined);setTab('overview');setProjects(await api('/v1/startup/projects'));setMessage('项目已删除')})}
 const fields=(group:string)=>(cap?.fields||[]).filter(f=>f.group===group).map(f=><label key={f.name}>{f.label}<textarea value={String(brief[f.name]??'')} maxLength={f.name==='evidence'?3000:f.name==='industry'?120:f.name==='entity_name'?160:f.name==='contact'||f.name==='target_market'?300:1500} rows={f.name==='industry'||f.name==='entity_name'||f.name==='contact'?2:3} onChange={e=>modify(f.name,e.target.value)} placeholder="填写真实资料，未确定的可留空"/></label>);
 return <div className="shell startup-shell"><PageHeading eyebrow="BUILD YOUR VENTURE" title="创业工作台" description="从商业验证开始，把项目、股权、资金与文稿放在同一个工作空间。"><Link className="button secondary" href="/data?path=entrepreneurship">创业政策</Link><Link className="button secondary" href={project?'/agent?intent=startup&startup_project_id='+project.id:'/agent?intent=startup'}><Icon name="spark" size={15}/>与校伴讨论</Link></PageHeading>
  <div className="startup-layout"><aside className="startup-projects"><button disabled={busy||loading} onClick={newProject}><Icon name="plus" size={15}/>新建创业项目</button><h2>我的项目</h2>{loading?<p>正在读取…</p>:!projects.length?<p className="field-hint">填写右侧概况，保存你的第一个项目。</p>:projects.map(p=><button className={'startup-project '+(project?.id===p.id?'active':'')} disabled={busy} key={p.id} onClick={()=>{if(abandon())void perform(()=>load(p.id))}}><b>{p.name}</b><small>{stages[p.stage]} · 资料 v{p.revision}</small></button>)}<p className="field-hint">项目和文稿按账号保存。文稿为讨论草稿；协议、股权与上市事项需结合实际条件核验。</p></aside>
  <section className="startup-main"><div className="startup-project-head"><div><span className="eyebrow">{project?'项目资料 v'+project.revision:'开始一个项目'}</span><h2>{brief.name||'你的创业想法'}</h2>{project&&<small className="field-hint">流程自评 {brief.completed_steps.length} / 10 · {stages[brief.stage]}</small>}</div>{project&&<button className="quiet" disabled={busy} onClick={()=>void remove()}>删除项目</button>}</div>
   <nav className="startup-tabs" aria-label="创业工作区">{tabs.map(([id,title])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} disabled={busy} onClick={()=>setTab(id)}>{title}</button>)}</nav>
   {error&&<p className="startup-feedback error" role="alert">{error}</p>}{message&&<p className="startup-feedback" role="status">{message}</p>}
   <form onSubmit={saveForm}><fieldset disabled={busy||loading} className="startup-fields">
    {tab==='overview'&&<><div className="startup-section-title"><h3>先把项目说清楚</h3><p>先填名称、客户和问题即可开始；后续逐步补齐证据。</p></div><div className="startup-form-grid"><label>项目名称<input required maxLength={160} value={brief.name} placeholder="为项目起一个名称" onChange={e=>modify('name',e.target.value)}/></label><label>项目阶段<select value={brief.stage} onChange={e=>modify('stage',e.target.value)}>{Object.entries(stages).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>主要经营法域<select value={brief.jurisdiction} onChange={e=>modify('jurisdiction',e.target.value)}><option value="CN">中国大陆</option><option value="HK">中国香港</option><option value="US">美国</option><option value="other">其他 / 待进一步确认</option></select></label>{fields('overview')}</div></>}
    {tab==='business'&&<><div className="startup-section-title"><h3>商业模式九要素与竞争位置</h3><p>把客户、价值、收费和交付连接起来，未验证的想法保留为假设。</p></div><div className="startup-form-grid">{fields('business')}</div><div className="button-row"><button type="button" onClick={()=>void generate('business_model')}>生成商业模式画布</button><button type="button" onClick={()=>void generate('architecture')}>生成商业架构</button><button type="button" onClick={()=>void generate('validation')}>生成 MVP 验证计划</button></div></>}
    {tab==='finance'&&<><div className="startup-section-title"><h3>财务假设</h3><p>所有金额使用同一币种。先看单位贡献和资金期限，再讨论融资。</p></div><div className="startup-form-grid">{financeFields.map(([key,label])=><label key={key}>{label}<input type="number" step="0.000001" min={key==='annual_volume_growth_pct'||key==='annual_cost_growth_pct'?-100:0} value={brief.finance[key]??''} onChange={e=>modify('finance',{...brief.finance,[key]:e.target.value===''?null:e.target.value})}/></label>)}</div><div className="startup-section-title"><h3>当前股权与贡献</h3><p>现有股东合计 100%。新期权池另行测算，不是登记资本或控制权结论。</p></div>{brief.founders.map((f,index)=><div className="startup-founder" key={index}><label>股东 {index+1} 名称<input required maxLength={80} value={f.name} onChange={e=>modify('founders',brief.founders.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/></label><label>当前比例 %<input required type="number" step="0.000001" min="0.000001" max="100" value={f.percent} onChange={e=>modify('founders',brief.founders.map((x,i)=>i===index?{...x,percent:e.target.value}:x))}/></label><label>角色<input maxLength={120} value={f.role} onChange={e=>modify('founders',brief.founders.map((x,i)=>i===index?{...x,role:e.target.value}:x))}/></label><label>实际贡献<input maxLength={500} value={f.contribution} onChange={e=>modify('founders',brief.founders.map((x,i)=>i===index?{...x,contribution:e.target.value}:x))}/></label><button type="button" aria-label={'移除股东 '+(index+1)} onClick={()=>modify('founders',brief.founders.filter((_,i)=>i!==index))}>移除</button></div>)}<div className="button-row"><button type="button" disabled={brief.founders.length>=20} onClick={()=>modify('founders',[...brief.founders,{name:'',role:'',percent:brief.founders.length?0:100,contribution:''}])}>添加股东</button><span>当前合计：{num(brief.founders.reduce((sum,f)=>sum+Number(f.percent),0))}%</span></div></>}
    {tab==='documents'&&<><div className="startup-section-title"><h3>文稿所需的主体与条款资料</h3><p>未填写的事实会保留为待补充。费用、数据处理和联系渠道须与实际服务一致。</p></div><details className="startup-details"><summary>补充主体、协议、数据和融资用途</summary><div className="startup-form-grid">{fields('documents')}</div></details></>}
    {tab==='roadmap'&&<><div className="startup-section-title"><h3>十个环节，按当前阶段推进</h3><p>初创先验证客户、交付和现金流；流程勾选只记录自评进度。资本化放在成长后期评估。</p></div><div className="startup-roadmap">{cap?.roadmap.map((s,index)=><div className="startup-step" key={s.id}><div><span className="startup-step-number">{index+1}</span><h4>{s.title}</h4><label className="startup-check"><input type="checkbox" checked={brief.completed_steps.includes(s.id)} onChange={e=>modify('completed_steps',e.target.checked?[...brief.completed_steps,s.id]:brief.completed_steps.filter(id=>id!==s.id))}/>已完成自评</label></div><ul>{s.tasks.map(t=><li key={t}>{t}</li>)}</ul><button type="button" onClick={()=>void generate(s.kind)}>生成相关文稿</button></div>)}</div></>}
    <div className="startup-savebar"><span className="field-hint">{dirty?'资料有未保存更改':project?'已保存资料；草稿版本单独保存':'填写名称后保存项目'}</span><button className="primary" type="submit">{busy?'处理中…':tab==='finance'?'保存并测算':'保存项目资料'}</button></div>
   </fieldset></form>
   {tab==='finance'&&analysis&&<div className="startup-analysis"><h3>测算结果 · 资料 v{analysis.project_revision}</h3>{dirty&&<p className="field-hint">输入已更改，下方仍是已保存资料的结果。请“保存并测算”。</p>}{analysis.economics.missing_fields.length?<p>请补齐单价、月销量、单位变动成本、固定支出和现金后测算。</p>:<><div className="startup-metrics">{[['月收入',analysis.economics.monthly_revenue],['月经营结果',analysis.economics.monthly_operating_result],['月资金消耗',analysis.economics.monthly_burn],['资金可维持月数',analysis.economics.runway_months],['盈亏平衡销量',analysis.economics.break_even_units],['单位贡献',analysis.economics.unit_contribution]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{num(value as number|null)}</b></div>)}</div><p className="field-hint">{analysis.economics.runway_note}</p><details className="startup-details"><summary>五年简化情景预测（基准及销量上下 20%）</summary><div className="startup-table-scroll"><table><thead><tr><th>情景</th><th>年</th><th>收入</th><th>成本</th><th>经营结果</th></tr></thead><tbody>{analysis.economics.projections?.map(p=><tr key={p.scenario+p.year}><td>{p.scenario}</td><td>{p.year}</td><td>{num(p.revenue)}</td><td>{num(p.cost)}</td><td>{num(p.operating_result)}</td></tr>)}</tbody></table></div></details></>}<h3>融资稀释场景</h3>{analysis.cap_table.rows.length?<div className="startup-table-scroll"><table><thead><tr><th>权益方</th><th>角色</th><th>当前 %</th><th>测算后 %</th></tr></thead><tbody>{analysis.cap_table.rows.map((r,index)=><tr key={index}><td>{r.name}</td><td>{r.role}</td><td>{num(r.before_pct)}</td><td>{num(r.after_pct)}</td></tr>)}</tbody></table></div>:<p>请填写股东比例；新增投资大于零时还需投前估值。</p>}<details className="startup-details"><summary>计算口径与适用边界</summary><ul>{[...analysis.economics.assumptions,...analysis.cap_table.assumptions].map(a=><li key={a}>{a}</li>)}</ul></details><div className="button-row"><button disabled={busy} onClick={()=>void generate('equity')}>生成股权设计</button><button disabled={busy} onClick={()=>void generate('finance')}>生成财务规划</button></div></div>}
   {tab==='documents'&&<div className="startup-document-center"><div className="startup-doc-tools"><label>文稿类型<select aria-label="文稿类型" value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{cap?.document_kinds.map(k=><option key={k.kind} value={k.kind}>{k.title}</option>)}</select></label><label>起草偏好<input maxLength={2000} value={instruction} disabled={busy} onChange={e=>setInstruction(e.target.value)} placeholder="如：面向潜在合伙人，优先分析风险"/></label><label className="startup-check"><input type="checkbox" checked={modelAssist} disabled={busy} onChange={e=>setModelAssist(e.target.checked)}/>使用已配置模型补充起草（发送本项目资料）</label><button className="primary" disabled={busy||loading} onClick={()=>void generate()}>{dirty||!project?'保存资料并生成草稿':'生成草稿'}</button></div>{instruction&&!modelAssist&&<p className="field-hint">规则草稿按项目资料生成；起草偏好在模型辅助模式中使用。</p>}
    {draft?<><div className="startup-draft-head"><h3>{draft.title}</h3><span className="badge">{draft.mode==='model_assisted'?'模型辅助草稿':'可编辑草稿'} · 资料 v{draft.project_revision}</span></div>{draft.model_notice&&<p className="field-hint">{draft.model_notice}</p>}<div className="button-row"><button disabled={busy} onClick={()=>setEdit(!edit)}>{edit?'阅读预览':'编辑文稿'}</button><button className="primary" disabled={busy} onClick={()=>void saveDraft()}>保存文稿版本</button><button disabled={busy} onClick={()=>{const url=URL.createObjectURL(new Blob([draft.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=draft.kind+'-draft.md';a.click();URL.revokeObjectURL(url)}}>下载 Markdown</button></div>{edit?<textarea className="startup-editor" aria-label="编辑创业文稿" value={draft.markdown} onChange={e=>{setDraft({...draft,markdown:e.target.value});setDocEdited(true)}} maxLength={80000}/>:<MarkdownDraft text={draft.markdown}/>}<div className="startup-references">{draft.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</div></>:<EmptyState title="选择一份文稿开始" description="商业画布、BP、股权与治理、用户协议、退出机制和 IPO 准备建议都可以生成、编辑并保存版本。"/>}
    <details className="startup-details" open><summary>已保存文稿与历史版本（{documents.length}）</summary><div className="startup-doc-history">{documents.map(d=><div key={d.id}><button disabled={busy} onClick={()=>void openDoc(d)}>{d.title} · v{d.version}</button><small>资料 v{d.project_revision} · {new Date(d.created_at).toLocaleDateString('zh-CN')}</small><a href={apiBase+'/v1/startup/projects/'+project?.id+'/documents/'+d.id+'/export'}>下载</a></div>)}{!documents.length&&<p className="field-hint">保存后的文稿会显示在这里。</p>}{moreDocs&&<button disabled={busy} onClick={()=>void perform(async()=>{const next=await api('/v1/startup/projects/'+project?.id+'/documents?offset='+documents.length);setDocuments(old=>[...old,...next]);setMoreDocs(next.length===100)})}>加载更多版本</button>}</div></details>
   </div>}
  </section></div>
 </div>
}
