import Link from 'next/link';
import {privateApi} from '@/lib/session-api';
import {PageHeading,TopicBar,streams,Icon,EmptyState} from '@/components/ui';
import type {PathRecord} from '@/lib/catalog';
type Node={id:number;title:string;month:string;grade:string;description:string};
export default async function Paths({searchParams}:{searchParams:Promise<{path?:string}>}){
 const p=await searchParams;const paths:PathRecord[]=await privateApi('/v1/paths');const selected=paths.find(x=>x.code===(p.path||streams[0].code))||paths[0];const nodes:Node[]=selected?await privateApi('/v1/paths/'+selected.id+'/timeline'):[];
 return <div className="shell"><PageHeading eyebrow="EXPLORE YOUR NEXT CHAPTER" title="发展路径指南" description="了解每个方向的准备重点，再选择适合自己的节奏。"/><div className="tabs">{streams.map(s=><Link key={s.code} href={'/paths?path='+s.code} className={selected?.code===s.code?'active':''}>{s.name}</Link>)}</div>{selected?<div className="workspace-columns"><div><section className="topic-section"><TopicBar title={selected.name} color={streams.find(s=>s.code===selected.code)?.color}/><div className="path-overview"><h2>{selected.description||selected.name}</h2><p>适合人群：{selected.target_group||'根据个人目标选择'} · 准备周期：{selected.duration||'根据项目要求安排'}</p><div className="button-row"><Link className="button primary" href={'/data?path='+selected.code}>查看相关信息<Icon name="arrow" size={14}/></Link>{process.env.ENABLE_AGENT_UI==='true'&&<Link className="button secondary" href={'/agent?intent=plan&path='+selected.code}>生成准备计划</Link>}</div></div></section><section className="topic-section"><TopicBar title="准备节点" color="#779b88"/>{nodes.length?<ol className="path-nodes">{nodes.map(n=><li key={n.id}><small>{n.grade} · {n.month}</small><strong>{n.title}</strong><p>{n.description}</p></li>)}</ol>:<EmptyState icon="calendar" title="该方向暂未配置参考节点" description="可查看相关公开事项，或在个人计划中自行安排准备进度。" href="/tracker" label="管理个人计划"/>}</section></div><aside className="context-rail"><section className="rail-tip"><Icon name="book" size={23}/><h3>参考节点与官方日程</h3><p>这里的节点帮助你安排准备节奏。实际报名时间、资格与材料要求，应以具体事项的官方通知为准。</p><Link href="/data/timeline">查看事项时间线 →</Link></section></aside></div>:<EmptyState title="暂未配置发展路径"/>}</div>
}
